# NLP Service
version: '3.8'

services:
  nlp-service:
    build: .
    container_name: nexus-nlp-service
    ports:
      - '8003:8003'
      - '9003:9003' # Metrics port
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8003
      - REDIS_URL=redis://redis:6379/2
      - CELERY_BROKER_URL=redis://redis:6379/3
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/var/log
      - ./temp:/tmp/nlp-service
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - nexus-network

  redis:
    image: redis:7-alpine
    container_name: nexus-nlp-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - nexus-network

  nlp-worker:
    build: .
    container_name: nexus-nlp-worker
    command: celery -A main.celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/3
      - CELERY_RESULT_BACKEND=redis://redis:6379/3
    volumes:
      - ./logs:/var/log
      - ./temp:/tmp/nlp-service
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - nexus-network

volumes:
  redis_data:

networks:
  nexus-network:
    external: true
