global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'nexus-ml-alerts@nexus-saude.com'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'
    - match:
        service: ml
      receiver: 'ml-team'

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://ml-service:8001/api/v1/monitoring/alerts/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@nexus-saude.com'
        subject: '[CRITICAL] Nexus ML Service Alert'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Service: {{ .CommonLabels.service }}

          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          {{ end }}
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#ml-alerts'
        title: 'Critical ML Service Alert'
        text: '{{ .CommonAnnotations.summary }}'

  - name: 'warning-alerts'
    email_configs:
      - to: 'ml-team@nexus-saude.com'
        subject: '[WARNING] Nexus ML Service Alert'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}

          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          {{ end }}

  - name: 'ml-team'
    webhook_configs:
      - url: 'http://ml-service:8001/api/v1/monitoring/alerts/webhook'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']
