# Prometheus configuration for Nexus Saúde ML Service
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'ml_alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # ML Service monitoring
  - job_name: 'nexus-ml-service'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ml-service:8001']
    scrape_timeout: 10s

  # System metrics (node_exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
