version: '3.8'

services:
  ml-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    environment:
      - ENV=development
      - LOG_LEVEL=info
      - DATABASE_URL=postgresql://nexus:nexus123@db:5432/nexus_saude
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    networks:
      - nexus-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=nexus_saude
      - POSTGRES_USER=nexus
      - POSTGRES_PASSWORD=nexus123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - nexus-network

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    networks:
      - nexus-network

  mlflow:
    image: python:3.11-slim
    command: >
      bash -c "pip install mlflow psycopg2-binary &&
               mlflow server --host 0.0.0.0 --port 5000 
               --backend-store-uri postgresql://nexus:nexus123@db:5432/mlflow
               --default-artifact-root /app/mlruns"
    ports:
      - '5000:5000'
    volumes:
      - mlflow_data:/app/mlruns
    depends_on:
      - db
    networks:
      - nexus-network

volumes:
  postgres_data:
  redis_data:
  mlflow_data:

networks:
  nexus-network:
    driver: bridge
